Pharma-main/src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column(length: 500)]
    private ?string $notice = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Type $type_produit = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $expirationDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getNotice(): ?string
    {
        return $this->notice;
    }

    public function setNotice(string $notice): self
    {
        $this->notice = $notice;

        return $this;
    }

    public function getTypeProduit(): ?Type
    {
        return $this->type_produit;
    }

    public function setTypeProduit(?Type $type_produit): self
    {
        $this->type_produit = $type_produit;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expirationDate;
    }

    public function setExpirationDate(?\DateTimeInterface $expirationDate): self
    {
        $this->expirationDate = $expirationDate;

        return $this;
    }
}

Pharma-main/src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('quantity')
            ->add('notice')
            ->add('image')
            ->add('type_produit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

Pharma-main/src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use App\Repository\TypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
            
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $produitRepository, TypeRepository $typeRepository): Response
    {
        $produit = new Produit();

        if(isset($_POST['submit'])){

            $nom = $request->request->get('nom');
            $prix = $request->request->get('prix');
            $qte = $request->request->get('qute');
            $notice = $request->request->get('notice');
            $image = $request->files->get('image');
            $type = $request->request->get('type');


            $produit->setName($nom);
            $produit->setPrice($prix);
            $produit->setQuantity(intval($qte));
            $produit->setNotice($notice);
            $produit->setTypeProduit($typeRepository->findOneBy(['description' => $type]));

            if($image){

                $newImage = uniqid() .'.'. $image->guessExtension();

                try{
                    $image->move(
                        $this->getParameter('kernel.project_dir') . '/public/images',
                        $newImage
                    );
                }catch (FileException $e){
                        return new Response($e->getMessage());                
                }
                    
                $produit->setImage($newImage);
            }
            
            $produitRepository->save($produit, true);
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }


        

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'types' => $typeRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, ProduitRepository $produitRepository, TypeRepository $typeRepository): Response
    {
        if(isset($_POST['submit'])){
            $nom = $request->request->get('nom');
            $prix = $request->request->get('prix');
            $qte = $request->request->get('qte');
            $notice = $request->request->get('notice');
            $image = $request->files->get('image');
            $type = $request->request->get('type');

        
            $produit->setName($nom);
            $produit->setPrice($prix);
            $produit->setQuantity($qte);
            $produit->setNotice($notice);
            $produit->setTypeProduit($typeRepository->findOneBy(['description' => $type]));

            if($image){

                $newImage = uniqid() .'.'. $image->guessExtension();

                try{
                    $image->move(
                        $this->getParameter('kernel.project_dir') . '/public/images',
                        $newImage
                    );
                }catch (FileException $e){
                        return new Response($e->getMessage());                
                }
                    
                $produit->setImage($newImage);
            }

            $produitRepository->save($produit, true);
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'types' => $typeRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $produitRepository->remove($produit, true);
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

Pharma-main/templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

Pharma-main/templates/produit/_edit_form.html.twig
{# {{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<style>
			.container {
				min-height: 317px;
				border: 5px solid #dddddd;
				display: flex;
				margin-top: 15px;
				align-items: center;
				justify-content: center;
				color: #cccccc
			}
            .image-preview{
                width: 100%;
                height : 317px;
            }
		</style>
		<div class="card">
			<div class="card-body">
				<form action="" method="POST" enctype="multipart/form-data">
					<div class="row mb-4">
						<div class="col">
							<fieldset>
								<legend>Informations néccessaires</legend>
								<label for="">Nom du produit</label>
								<input type="text" name="nom" id="" class="form-control mb-4" value="{{produit.name}}">

								<label for="">Prix du produit</label>
								<input type="number" name="prix" id="" class="form-control mb-4" value="{{produit.price}}">

								<label for="">Quantité du produit</label>
								<input type="number" name="qte" id="" class="form-control mb-4" value="{{produit.quantity}}">

								<label for="">Utilisation du produit</label>
								<input type="text" name="notice" id="" class="form-control mb-4" value="{{produit.notice}}">

								<label for="">Type du produit</label>
								<select name="type" id="" class="form-select">
									{% for type in types %}
										<option {% if produit.typeProduit.description == type.description %} selected {% endif %} value="{{type.description}}">{{type.description}}</option>
									{% endfor %}
								</select>

							</fieldset>
						</div>
						<div class="col">
							<fieldset>
								<legend>Image du produit</legend>
								<label for="">Image</label>
								<input type="file" name="image" class="form-control" id="inpFile">
								<div class="container" id="container">
									{% if produit.image %}
										<img src="{{asset('images/')}}{{produit.image}}" alt="" srcset="" class="image-preview">
									{% else %}
										<img src="" alt="" srcset="" class="image-preview">
										<span class="image-preview-text">
											Apercu de la photo
										</span>
									{% endif %}
									
								</div>
							</fieldset>
						</div>

					</div>
					<input type="date" name="expiration" id="" class="form-control" value="{{produit.expirationDate ? produit.expirationDate|date('Y-m-d') : ''}}">
					<input type="submit" value="Enregistrer" name="submit" class="btn btn-primary mt-4">
				</form>
			</div>
		</div>
	</body>

	<script>
		const inpFile = document.getElementById("inpFile");
        const container = document.getElementById("container");
        const preview = container.querySelector(".image-preview");
        const text = container.querySelector(".image-preview-text");
        inpFile.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
        const reader = new FileReader();
        text.style.display = "none";
        preview.style.display = "block";

        reader.addEventListener("load", function () {
        preview.setAttribute("src", this.result);
        });

        reader.readAsDataURL(file);
        } else {
        text.style.display = null;
        preview.style.display = null;
        }
        });
	</script>
</html>

Pharma-main/templates/produit/_form.html.twig
{# {{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<style>
			.container {
				min-height: 317px;
				border: 5px solid #dddddd;
				display: flex;
				margin-top: 15px;
				align-items: center;
				justify-content: center;
				color: #cccccc
			}
            .image-preview{
                display: none;
                width: 100%;
                height : 317px;
            }
		</style>
		<div class="card">
			<div class="card-body">
				<form action="" method="POST" enctype="multipart/form-data">
					<div class="row mb-4">
						<div class="col">
							<fieldset>
								<legend>Informations néccessaires</legend>
								<label for="">Nom du produit</label>
								<input type="text" name="nom" id="" class="form-control mb-4">

								<label for="">Prix du produit</label>
								<input type="number" name="prix" id="" class="form-control mb-4">

								<label for="">Quantité du produit</label>
								<input type="number" name="qte" id="" class="form-control mb-4">

								<label for="">Utilisation du produit</label>
								<input type="text" name="notice" id="" class="form-control mb-4">

								<label for="">Type du produit</label>
								<select name="type" id="" class="form-select">
									{% for type in types %}
										<option value="{{type.description}}">{{type.description}}</option>
									{% endfor %}
								</select>

							</fieldset>
						</div>
						<div class="col">
							<fieldset>
								<legend>Image du produit</legend>
								<label for="">Image</label>
								<input type="file" name="image" class="form-control" id="inpFile">
								<div class="container" id="container">
									<img src="  " alt="" srcset="" class="image-preview">
									<span class="image-preview-text">
										Apercu de la photo
									</span>
								</div>
							</fieldset>
						</div>

					</div>
                    <label for="">Date d'expiration</label>
                    <input type="date" name="expiration" id="" class="form-control mb-4">
					<input type="submit" value="Enregistrer" name="submit" class="btn btn-primary">
				</form>
			</div>
		</div>
	</body>

	<script>
		const inpFile = document.getElementById("inpFile");
        const container = document.getElementById("container");
        const preview = container.querySelector(".image-preview");
        const text = container.querySelector(".image-preview-text");
        inpFile.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
        const reader = new FileReader();
        text.style.display = "none";
        preview.style.display = "block";

        reader.addEventListener("load", function () {
        preview.setAttribute("src", this.result);
        });

        reader.readAsDataURL(file);
        } else {
        text.style.display = null;
        preview.style.display = null;
        }
        });
	</script>
</html>

Pharma-main/templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_edit_form.html.twig')}}

    <a href="{{ path('app_produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

Pharma-main/templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Notice</th>
                <th>Expiration</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.name }}</td>
                <td>{{ produit.price }}</td>
                <td>{{ produit.quantity }}</td>
                <td>{{ produit.notice }}</td>
                <td>{{ produit.expirationDate ? produit.expirationDate|date('Y-m-d') : '' }}</td>
                <td>{{ produit.image }}</td>
                <td>
                    <a href="{{ path('app_produit_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        {% for produit in produits %}            
            <div class="row">
            <div class="col-sm-6 col-xl-3">
                <div class="card overflow-hidden rounded-2">
                <div class="position-relative">
                    <a href="javascript:void(0)"><img src="{{asset('images/')}}{{produit.image}}" class="card-img-top rounded-0" alt="..."></a>
                <div class="card-body pt-3 p-4">
                    <h6 class="fw-semibold fs-4">{{produit.name}}</h6>
                    <div class="d-flex align-items-center justify-content-between">
                        <h6 class="fw-semibold fs-4 mb-0">{{produit.price}} FCFA<span class="ms-2 fw-normal text-muted fs-3"></span></h6>
                        {% if produit.quantity >= 2 %}
                            <button class="btn  btn-success">Stock({{produit.quantity}})</button>
                        {% else %}
                            <button class="btn  btn-danger">Stock({{produit.quantity}})</button>
                        {% endif %}
                    </div>
                    <div class="d-flex align-items-center justify-content-between mt-4">
                        <a href="{{ path('app_produit_show', {'id': produit.id}) }}" class="btn btn-outline-primary">Detail</a>
                        <a href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn btn-outline-success">Modifier</a>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}

    <a href="{{ path('app_produit_new') }}">Create new</a>
{% endblock %}

Pharma-main/templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}">back to list</a>
{% endblock %}

Pharma-main/templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ produit.name }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ produit.price }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ produit.quantity }}</td>
            </tr>
            <tr>
                <th>Notice</th>
                <td>{{ produit.notice }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ produit.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produit_index') }}">back to list</a>

    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}